data_source input_db:
  type: postgres
  connection:
    host: input_db
    port: '5432'
    username: postgres
    password: postgres
  database: postgres
  schema: public

data_source output_db:
  type: postgres
  connection:
    host: output_db
    port: '5432'
    username: postgres
    password: postgres
  database: postgres
  schema: public
