services:

  check_env_ready:
    platform: linux/amd64
    container_name: check_env_setup
    image: sodadata/soda-core
    command: scan -d output_db -c /root/.soda/configuration.yaml /root/.soda/checks.yaml
    volumes:
      - ./database_configuration.yaml:/root/.soda/configuration.yaml
      - ./soda/checks_for_setup.yaml:/root/.soda/checks.yaml

  check_challenge_1:
    platform: linux/amd64
    container_name: check_challenge_1
    image: sodadata/soda-core
    command: scan -d output_db -c /root/.soda/configuration.yaml /root/.soda/checks.yaml
    volumes:
      - ./database_configuration.yaml:/root/.soda/configuration.yaml
      - ./soda/checks_for_masking.yaml:/root/.soda/checks.yaml

  check_challenge_2:
    container_name: check_challenge_2
    image: sodadata/soda-core
    command: scan -d output_db -c /root/.soda/configuration.yaml /root/.soda/checks.yaml
    volumes:
      - ./database_configuration.yaml:/root/.soda/configuration.yaml
      - ./soda/checks_for_generation.yaml:/root/.soda/checks.yaml

  check_challenge_3:
    container_name: check_challenge_3
    image: sodadata/soda-core
    command: scan -d output_db -c /root/.soda/configuration.yaml /root/.soda/checks.yaml
    volumes:
      - ./database_configuration.yaml:/root/.soda/configuration.yaml
      - ./soda/checks_for_transformation.yaml:/root/.soda/checks.yaml      
